"""conversations and the two-sided handshake

One conversation per offer, holding the deal on the table and the two
signatures on it. The version column is what makes a signature specific:
agreeing to version 4 says nothing about version 5, so a price moved after
somebody signed is a price nobody has signed.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-02 22:25:18.755142+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('offer_id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('price_centimes', sa.BigInteger(), nullable=False),
    sa.Column('terms', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('client_agreed_version', sa.Integer(), nullable=True),
    sa.Column('provider_agreed_version', sa.Integer(), nullable=True),
    sa.Column('sealed_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('client_read_at', sa.DateTime(), nullable=True),
    sa.Column('provider_read_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_conversations_client_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_conversations_offer_id_offers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_profiles.id'], name=op.f('fk_conversations_provider_id_provider_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_conversations_request_id_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('offer_id', name='uq_conversations_offer_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_conversations_client_id'), 'conversations', ['client_id'], unique=False)
    op.create_index(op.f('ix_conversations_offer_id'), 'conversations', ['offer_id'], unique=False)
    op.create_index(op.f('ix_conversations_provider_id'), 'conversations', ['provider_id'], unique=False)
    op.create_index(op.f('ix_conversations_request_id'), 'conversations', ['request_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.Enum('text', 'image', 'file', 'system', name='messagekind', native_enum=False, length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('redacted_count', sa.Integer(), nullable=False),
    sa.Column('attachment_path', sa.String(length=500), nullable=True),
    sa.Column('attachment_name', sa.String(length=255), nullable=True),
    sa.Column('attachment_bytes', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_conversation_messages_sender_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_messages')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_conversations_request_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_provider_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_offer_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_client_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
