"""unread by message id, not by clock

These columns are DATETIME to the second, so a reply landing in the same second
as the read compared as "not newer" and the badge never appeared. Message ids
are monotonic and exact. Nothing else read the timestamps, so they go.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-04 17:15:15.675447+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('client_read_message_id', sa.BigInteger(), nullable=True))
    op.add_column('conversations', sa.Column('provider_read_message_id', sa.BigInteger(), nullable=True))
    op.drop_column('conversations', 'client_read_at')
    op.drop_column('conversations', 'provider_read_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('provider_read_at', mysql.DATETIME(), nullable=True))
    op.add_column('conversations', sa.Column('client_read_at', mysql.DATETIME(), nullable=True))
    op.drop_column('conversations', 'provider_read_message_id')
    op.drop_column('conversations', 'client_read_message_id')
    # ### end Alembic commands ###
