"""the lead fee can be paid by revealing a contact

A tradesman may hand over his phone number in the chat instead of waiting for
the handshake. It is the same lead and it costs the same fee, taken at that
moment; this column records when, so contacts stop being struck out and the
handshake knows not to charge him twice.

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-04 20:12:16.291822+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('lead_charged_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'lead_charged_at')
    # ### end Alembic commands ###
