"""contacts are struck out again, and never charged for

The lead fee is charged once, at the handshake, and there is no longer a
second door a tradesman can pay his way through. He may type his number; it
is struck out of the message, quietly, and counted. `lead_charged_at` was
the record of a price that no longer exists.

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-04 21:28:26.279640+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'lead_charged_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('lead_charged_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
