"""the platform can file a report

A tradesman who keeps trying to hand his number to client after client is
flagged to staff by the system rather than by a person, so `reporter_id`
becomes nullable. Its absence is the signal: a staff screen reads it as
"noticed automatically", which is a different weight from an accusation
somebody put their name to.

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-04 21:42:10.784440+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'reporter_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'reporter_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
    # ### end Alembic commands ###
