"""paid placement

A tradesman may buy thirty days at the top of the search results. The column
holds when that runs out, and running out is a comparison against the clock —
there is nothing to sweep and no job to forget to run. Indexed because every
listing query orders by it.

Being listed stays free. This buys position and a badge saying so, and
nothing else: not a rating, not a competitor's absence.

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-04 22:02:32.729275+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Autogenerate reaches for `mysql.DATETIME()` and friends when it writes a
# downgrade and never imports them, so a generated file would be born broken.
from sqlalchemy.dialects import mysql

revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_profiles', sa.Column('boosted_until', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_provider_profiles_boosted_until'), 'provider_profiles', ['boosted_until'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_profiles_boosted_until'), table_name='provider_profiles')
    op.drop_column('provider_profiles', 'boosted_until')
    # ### end Alembic commands ###
