"""a tradesman can pause

A plumber on holiday kept appearing in search, kept being asked, and kept not
answering. `accepting_work` is what he typed; `back_on` is when the pause
lifts itself, so a switch he forgets does not create the opposite problem.

Whether he is available *today* is computed from the two, never stored — a
stored answer goes stale the moment the date passes.

Existing rows default to accepting work, which is what they were doing.

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-05 13:41:16.663209+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Autogenerate reaches for `mysql.DATETIME()` and friends when it writes a
# downgrade and never imports them, so a generated file would be born broken.
from sqlalchemy.dialects import mysql

revision: str = '0009'
down_revision: str | None = '0008'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # `server_default` matters here and nowhere else in this file: the model's
    # default is Python-side, so without it MySQL fills every existing row with
    # false and pauses every tradesman on the platform at deploy time.
    op.add_column(
        'provider_profiles',
        sa.Column(
            'accepting_work', sa.Boolean(), nullable=False, server_default=sa.true()
        ),
    )
    op.add_column('provider_profiles', sa.Column('back_on', sa.Date(), nullable=True))
    op.create_index(op.f('ix_provider_profiles_accepting_work'), 'provider_profiles', ['accepting_work'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_profiles_accepting_work'), table_name='provider_profiles')
    op.drop_column('provider_profiles', 'back_on')
    op.drop_column('provider_profiles', 'accepting_work')
    # ### end Alembic commands ###
